// <auto-generated />
using System;
using AssignmentService.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AssignmentDbContext))]
    [Migration("20251104134113_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssignmentService.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assignment_id");

                    b.Property<bool>("AllowLateSubmission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_late_submission");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_by");

                    b.Property<string>("AssignmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("assignment_type");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<int?>("TotalPoints")
                        .HasColumnType("int")
                        .HasColumnName("total_points");

                    b.HasKey("AssignmentId")
                        .HasName("pk_assignment");

                    b.HasIndex("AssignedBy")
                        .HasDatabaseName("ix_assignment_assigned_by");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_assignment_class_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_assignment_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_assignment_status");

                    b.ToTable("assignment", (string)null);
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.AssignmentProblem", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assignment_id");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("problem_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100)
                        .HasColumnName("points");

                    b.HasKey("AssignmentId", "ProblemId")
                        .HasName("pk_assignment_problem");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_assignment_problem_assignment_id");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_assignment_problem_problem_id");

                    b.ToTable("assignment_problem", (string)null);
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.AssignmentUser", b =>
                {
                    b.Property<Guid>("AssignmentUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assignment_user_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assignment_id");

                    b.Property<int?>("MaxScore")
                        .HasColumnType("int")
                        .HasColumnName("max_score");

                    b.Property<int?>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("AssignmentUserId")
                        .HasName("pk_assignment_user");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_assignment_user_assignment_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_assignment_user_user_id");

                    b.ToTable("assignment_user", (string)null);
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.BestSubmission", b =>
                {
                    b.Property<Guid>("AssignmentUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assignment_user_id");

                    b.Property<Guid>("BestSubmissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("best_submission_id");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int")
                        .HasColumnName("max_score");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("problem_id");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("submission_id");

                    b.Property<long>("TotalMemory")
                        .HasColumnType("bigint")
                        .HasColumnName("total_memory");

                    b.Property<long>("TotalTime")
                        .HasColumnType("bigint")
                        .HasColumnName("total_time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.ToTable((string)null);

                    b.ToView("BestSubmissions", (string)null);
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Dataset", b =>
                {
                    b.Property<Guid>("DatasetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("dataset_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("problem_id");

                    b.HasKey("DatasetId")
                        .HasName("pk_dataset");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_datasets_problemid");

                    b.ToTable("dataset", (string)null);
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DefaultBody")
                        .HasMaxLength(4000)
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("default_body");

                    b.Property<string>("DefaultHead")
                        .HasMaxLength(4000)
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("default_head");

                    b.Property<int?>("DefaultMemoryKb")
                        .HasColumnType("int")
                        .HasColumnName("default_memory_kb");

                    b.Property<string>("DefaultTail")
                        .HasMaxLength(4000)
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("default_tail");

                    b.Property<decimal>("DefaultTimeFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("default_time_factor");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.HasKey("LanguageId")
                        .HasName("pk_language");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_language_code");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_language_display_order");

                    b.ToTable("language", (string)null);
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Problem", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("problem_id");

                    b.Property<string>("Changelog")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("changelog");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Constraints")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("constraints");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("difficulty");

                    b.Property<string>("InputFormat")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("input_format");

                    b.Property<string>("IoMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasDefaultValue("STDIO")
                        .HasColumnName("io_mode");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_locked");

                    b.Property<int?>("MaxScore")
                        .HasColumnType("int")
                        .HasColumnName("max_score");

                    b.Property<int>("MemoryLimitKb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(262144)
                        .HasColumnName("memory_limit_kb");

                    b.Property<string>("OutputFormat")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("output_format");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_id");

                    b.Property<string>("SampleInput")
                        .HasMaxLength(4000)
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("sample_input");

                    b.Property<string>("SampleOutput")
                        .HasMaxLength(4000)
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("sample_output");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Solution")
                        .HasMaxLength(4000)
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("solution");

                    b.Property<int>("SourceLimitKb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(65536)
                        .HasColumnName("source_limit_kb");

                    b.Property<int>("StackLimitKb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(8192)
                        .HasColumnName("stack_limit_kb");

                    b.Property<string>("Statement")
                        .HasMaxLength(4000)
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("statement");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("status");

                    b.Property<int>("TimeLimitMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1000)
                        .HasColumnName("time_limit_ms");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ValidatorRef")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("validator_ref");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("visibility");

                    b.HasKey("ProblemId")
                        .HasName("pk_problem");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_problems_code");

                    b.HasIndex("Difficulty")
                        .HasDatabaseName("ix_problems_difficulty");

                    b.HasIndex("IsLocked")
                        .HasDatabaseName("ix_problems_islocked");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_problems_ownerid");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_problems_slug");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_problems_title");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_problems_updatedat");

                    b.HasIndex("Status", "Visibility")
                        .HasDatabaseName("ix_problems_status_visibility");

                    b.ToTable("problem", (string)null);
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.ProblemAsset", b =>
                {
                    b.Property<Guid>("ProblemAssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("problem_asset_id");

                    b.Property<string>("Checksum")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("checksum");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Format")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("MARKDOWN")
                        .HasColumnName("format");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ObjectRef")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("object_ref");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("order_index");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("problem_id");

                    b.Property<string>("Title")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("type");

                    b.HasKey("ProblemAssetId")
                        .HasName("pk_problem_asset");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_problemassets_problemid");

                    b.HasIndex("ProblemId", "Type", "OrderIndex")
                        .HasDatabaseName("ix_problemassets_problemid_type_orderindex");

                    b.ToTable("problem_asset", (string)null);
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.ProblemLanguage", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("language_id");

                    b.Property<string>("BodyOverride")
                        .HasMaxLength(4000)
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("body_override");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("HeadOverride")
                        .HasMaxLength(4000)
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("head_override");

                    b.Property<bool>("IsAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_allowed");

                    b.Property<int?>("MemoryKbOverride")
                        .HasColumnType("int")
                        .HasColumnName("memory_kb_override");

                    b.Property<string>("TailOverride")
                        .HasMaxLength(4000)
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("tail_override");

                    b.Property<decimal?>("TimeFactorOverride")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("time_factor_override");

                    b.HasKey("ProblemId", "LanguageId")
                        .HasName("pk_problem_language");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_problem_language_language");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_problem_language_problem");

                    b.ToTable("problem_language", (string)null);
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.ProblemTag", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tag_id");

                    b.HasKey("ProblemId", "TagId")
                        .HasName("pk_problem_tag");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_problem_tag_tag_id");

                    b.ToTable("problem_tag", (string)null);
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("submission_id");

                    b.Property<Guid?>("AssignmentUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assignment_user_id");

                    b.Property<string>("CompareResult")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("compare_result");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("dataset_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("error_message");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("language");

                    b.Property<int>("PassedTestcase")
                        .HasColumnType("int")
                        .HasColumnName("passed_testcase");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("problem_id");

                    b.Property<string>("ResultFileRef")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("result_file_ref");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("source_code");

                    b.Property<string>("SourceCodeRef")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("source_code_ref");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<long>("TotalMemory")
                        .HasColumnType("bigint")
                        .HasColumnName("total_memory");

                    b.Property<int>("TotalTestcase")
                        .HasColumnType("int")
                        .HasColumnName("total_testcase");

                    b.Property<long>("TotalTime")
                        .HasColumnType("bigint")
                        .HasColumnName("total_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("SubmissionId")
                        .HasName("pk_submission");

                    b.HasIndex("AssignmentUserId")
                        .HasDatabaseName("ix_submission_assignment_user_id");

                    b.HasIndex("DatasetId")
                        .HasDatabaseName("ix_submission_dataset_id");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_submission_problem_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_submission_status");

                    b.HasIndex("SubmittedAt")
                        .HasDatabaseName("ix_submission_submitted_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_submission_user_id");

                    b.ToTable("submission", (string)null);
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tag_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name");

                    b.HasKey("TagId")
                        .HasName("pk_tag");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_tag_category");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tag_name");

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.TestCase", b =>
                {
                    b.Property<Guid>("TestCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("test_case_id");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("dataset_id");

                    b.Property<int>("IndexNo")
                        .HasColumnType("int")
                        .HasColumnName("index_no");

                    b.Property<string>("InputRef")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("input_ref");

                    b.Property<string>("OutputRef")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("output_ref");

                    b.Property<string>("Score")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("100")
                        .HasColumnName("score");

                    b.HasKey("TestCaseId")
                        .HasName("pk_test_case");

                    b.HasIndex("DatasetId", "IndexNo")
                        .IsUnique()
                        .HasDatabaseName("ix_test_case_dataset_id_index_no");

                    b.ToTable("test_case", (string)null);
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.AssignmentProblem", b =>
                {
                    b.HasOne("AssignmentService.Domain.Entities.Assignment", "Assignment")
                        .WithMany("AssignmentProblems")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_problem_assignment_assignment_id");

                    b.HasOne("AssignmentService.Domain.Entities.Problem", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_problem_problem_problem_id");

                    b.Navigation("Assignment");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.AssignmentUser", b =>
                {
                    b.HasOne("AssignmentService.Domain.Entities.Assignment", "Assignment")
                        .WithMany("AssignmentUsers")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_user_assignment_assignment_id");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Dataset", b =>
                {
                    b.HasOne("AssignmentService.Domain.Entities.Problem", "Problem")
                        .WithMany("Datasets")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dataset_problem_problem_id");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.ProblemAsset", b =>
                {
                    b.HasOne("AssignmentService.Domain.Entities.Problem", "Problem")
                        .WithMany("ProblemAssets")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_asset_problem_problem_id");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.ProblemLanguage", b =>
                {
                    b.HasOne("AssignmentService.Domain.Entities.Language", "Language")
                        .WithMany("ProblemLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_problem_language_language");

                    b.HasOne("AssignmentService.Domain.Entities.Problem", "Problem")
                        .WithMany("ProblemLanguages")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_language_problem");

                    b.Navigation("Language");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.ProblemTag", b =>
                {
                    b.HasOne("AssignmentService.Domain.Entities.Problem", "Problem")
                        .WithMany("ProblemTags")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_tag_problem_problem_id");

                    b.HasOne("AssignmentService.Domain.Entities.Tag", "Tag")
                        .WithMany("ProblemTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_tag_tag_tag_id");

                    b.Navigation("Problem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Submission", b =>
                {
                    b.HasOne("AssignmentService.Domain.Entities.AssignmentUser", "AssignmentUser")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_submission_assignment_user_assignment_user_id");

                    b.HasOne("AssignmentService.Domain.Entities.Problem", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submission_problem_problem_id");

                    b.Navigation("AssignmentUser");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.TestCase", b =>
                {
                    b.HasOne("AssignmentService.Domain.Entities.Dataset", "Dataset")
                        .WithMany("TestCases")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_case_dataset_dataset_id");

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Assignment", b =>
                {
                    b.Navigation("AssignmentProblems");

                    b.Navigation("AssignmentUsers");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.AssignmentUser", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Dataset", b =>
                {
                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Language", b =>
                {
                    b.Navigation("ProblemLanguages");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Problem", b =>
                {
                    b.Navigation("Datasets");

                    b.Navigation("ProblemAssets");

                    b.Navigation("ProblemLanguages");

                    b.Navigation("ProblemTags");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Tag", b =>
                {
                    b.Navigation("ProblemTags");
                });
#pragma warning restore 612, 618
        }
    }
}
