// <auto-generated />
using System;
using AssignmentService.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AssignmentDbContext))]
    partial class AssignmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssignmentService.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowLateSubmission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("DRAFT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TotalPoints")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("ClassId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.AssignmentProblem", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.HasKey("AssignmentId", "ProblemId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("ProblemId");

                    b.ToTable("AssignmentProblems");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.AssignmentUser", b =>
                {
                    b.Property<Guid>("AssignmentUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MaxScore")
                        .HasColumnType("int");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssignmentUserId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("UserId");

                    b.ToTable("AssignmentUsers");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.BestSubmission", b =>
                {
                    b.Property<Guid>("BestSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignmentUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TotalMemory")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalTime")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("BestSubmissionId");

                    b.HasIndex("AssignmentUserId");

                    b.HasIndex("ProblemId");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("AssignmentUserId", "ProblemId")
                        .IsUnique();

                    b.ToTable("BestSubmissions");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.CodeTemplate", b =>
                {
                    b.Property<Guid>("CodeTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StarterRef")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("CodeTemplateId");

                    b.HasIndex("Lang")
                        .HasDatabaseName("ix_codetemplates_lang");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_codetemplates_problemid");

                    b.ToTable("CodeTemplates");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Dataset", b =>
                {
                    b.Property<Guid>("DatasetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DatasetId");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_datasets_problemid");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.LanguageLimit", b =>
                {
                    b.Property<Guid>("LanguageLimitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MemoryKbOverride")
                        .HasColumnType("int");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TimeFactor")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("LanguageLimitId");

                    b.HasIndex("Lang")
                        .HasDatabaseName("ix_languagelimits_lang");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_languagelimits_problemid");

                    b.HasIndex("ProblemId", "Lang")
                        .IsUnique()
                        .HasDatabaseName("ix_languagelimits_problemid_lang");

                    b.ToTable("LanguageLimits");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Problem", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Changelog")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Constraints")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("InputFormat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IoMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasDefaultValue("STDIO");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("MaxScore")
                        .HasColumnType("int");

                    b.Property<int>("MemoryLimitKb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(262144);

                    b.Property<string>("OutputFormat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SampleInput")
                        .HasMaxLength(4000)
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("SampleOutput")
                        .HasMaxLength(4000)
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SourceLimitKb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(65536);

                    b.Property<int>("StackLimitKb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(8192);

                    b.Property<string>("StatementMdRef")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("TimeLimitMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1000);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("ValidatorRef")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("ProblemId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_problems_code");

                    b.HasIndex("Difficulty")
                        .HasDatabaseName("ix_problems_difficulty");

                    b.HasIndex("IsLocked")
                        .HasDatabaseName("ix_problems_islocked");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_problems_ownerid");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_problems_slug");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_problems_title");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_problems_updatedat");

                    b.HasIndex("Status", "Visibility")
                        .HasDatabaseName("ix_problems_status_visibility");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.ProblemAsset", b =>
                {
                    b.Property<Guid>("ProblemAssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Checksum")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("ObjectRef")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("ProblemAssetId");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_problemassets_problemid");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_problemassets_type");

                    b.ToTable("ProblemAssets");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.ProblemTag", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProblemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProblemTags");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompareResult")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PassedTestcase")
                        .HasColumnType("int");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResultFileRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceCodeRef")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<long>("TotalMemory")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalTestcase")
                        .HasColumnType("int");

                    b.Property<long>("TotalTime")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SubmissionId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("DatasetId");

                    b.HasIndex("ProblemId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("TagId");

                    b.HasIndex("Category");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.TestCase", b =>
                {
                    b.Property<Guid>("TestCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IndexNo")
                        .HasColumnType("int");

                    b.Property<string>("InputRef")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OutputRef")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Score")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("100");

                    b.HasKey("TestCaseId");

                    b.HasIndex("DatasetId", "IndexNo")
                        .IsUnique();

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.AssignmentProblem", b =>
                {
                    b.HasOne("AssignmentService.Domain.Entities.Assignment", "Assignment")
                        .WithMany("AssignmentProblems")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssignmentService.Domain.Entities.Problem", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.AssignmentUser", b =>
                {
                    b.HasOne("AssignmentService.Domain.Entities.Assignment", "Assignment")
                        .WithMany("AssignmentUsers")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.BestSubmission", b =>
                {
                    b.HasOne("AssignmentService.Domain.Entities.AssignmentUser", "AssignmentUser")
                        .WithMany("BestSubmissions")
                        .HasForeignKey("AssignmentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssignmentService.Domain.Entities.Problem", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssignmentService.Domain.Entities.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignmentUser");

                    b.Navigation("Problem");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.CodeTemplate", b =>
                {
                    b.HasOne("AssignmentService.Domain.Entities.Problem", "Problem")
                        .WithMany("CodeTemplates")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Dataset", b =>
                {
                    b.HasOne("AssignmentService.Domain.Entities.Problem", "Problem")
                        .WithMany("Datasets")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.LanguageLimit", b =>
                {
                    b.HasOne("AssignmentService.Domain.Entities.Problem", "Problem")
                        .WithMany("LanguageLimits")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.ProblemAsset", b =>
                {
                    b.HasOne("AssignmentService.Domain.Entities.Problem", "Problem")
                        .WithMany("ProblemAssets")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.ProblemTag", b =>
                {
                    b.HasOne("AssignmentService.Domain.Entities.Problem", "Problem")
                        .WithMany("ProblemTags")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssignmentService.Domain.Entities.Tag", "Tag")
                        .WithMany("ProblemTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.TestCase", b =>
                {
                    b.HasOne("AssignmentService.Domain.Entities.Dataset", "Dataset")
                        .WithMany("TestCases")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Assignment", b =>
                {
                    b.Navigation("AssignmentProblems");

                    b.Navigation("AssignmentUsers");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.AssignmentUser", b =>
                {
                    b.Navigation("BestSubmissions");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Dataset", b =>
                {
                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Problem", b =>
                {
                    b.Navigation("CodeTemplates");

                    b.Navigation("Datasets");

                    b.Navigation("LanguageLimits");

                    b.Navigation("ProblemAssets");

                    b.Navigation("ProblemTags");
                });

            modelBuilder.Entity("AssignmentService.Domain.Entities.Tag", b =>
                {
                    b.Navigation("ProblemTags");
                });
#pragma warning restore 612, 618
        }
    }
}
