FROM debian:bookworm-slim

# Cài Python & toolchain build
RUN apt-get update && apt-get install -y \
    python3 python3-pip\
    git \
    build-essential \
    pkg-config \
    libcap-dev \
    libsystemd-dev \
    && rm -rf /var/lib/apt/lists/*

# Build Isolate
RUN git clone https://github.com/ioi/isolate.git /opt/isolate \
    && cd /opt/isolate \
    && make install

# Tạo thư mục runtime cho isolate
RUN mkdir -p /var/local/lib/isolate \
    && chmod 711 /var/local/lib/isolate

# Copy project code
WORKDIR /app
COPY requirements.txt .
RUN pip3 install --break-system-packages --no-cache-dir -r requirements.txt
COPY . .

CMD ["python3", "-m", "app.main"]
