FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dev
WORKDIR /app

# Install EF Core Tools
RUN dotnet nuget locals all --clear && \
    dotnet tool install --global dotnet-ef --version 8.0.11

ENV PATH="${PATH}:/root/.dotnet/tools"

# Copy các project để restore dependency
COPY ["Api/Api.csproj", "Api/"]
COPY ["Application/Application.csproj", "Application/"]
COPY ["Domain/Domain.csproj", "Domain/"]
COPY ["Infrastructure/Infrastructure.csproj", "Infrastructure/"]

RUN dotnet restore "Api/Api.csproj"

# Copy toàn bộ source code
COPY . .
EXPOSE 5002

# Chạy dev mode
CMD ["dotnet", "run", "--project", "Api/Api.csproj", "--urls", "http://0.0.0.0:5002"]
